IMDB/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace IMDB.Models
{
    public class User 
    {

        [Key]
        public int User_ID { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "First Name")]
        public string Fname { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Second Name")]
        public string Lname { get; set; }

        [FileExtensions(Extensions = "jpg,jpeg,png")]
        [DataType(DataType.ImageUrl)]
        [Display(Name = "User Image")]
        public string Image { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Email Address")]
        public string Email { get; set; }

        [Required]
        [StringLength(50)]
        [Compare("Email", ErrorMessage = "The email and confirmation email do not match.")]
        public string ConfirmEmail { get; set; }

        [Required]
        [StringLength(50)]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required]
        [StringLength(50)]
        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }

        [Required]
        public UserGender Gender { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Birthday { get; set; }



    }

    public enum UserGender
    {
        Male,
        Female
    }
}

IMDB/ViewModels/EditProfile.cs
using IMDB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IMDB.ViewModels
{
    public class EditProfile
    {

        public User User { get; set; }
        public User TempUser { get; set; }
        public List<FavouriteActor> FavouriteActors { get; set; }
        public List<FavouriteDirector> FavouriteDirectors { get; set; }
        public List<FavouriteMovie> FavouriteMovies { get; set; }

        public List<int> FavouriteActorsIds { get; set; }
        public List<int> FavouriteDirectorsIds { get; set; }
        public List<int> FavouriteMoviesIds { get; set; }

        public List<Actor> Actors { get; set; }
        public List<Director> Directors { get; set; }
        public List<Movie> Movies { get; set; }

    }
}

IMDB/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.Security;
using IMDB.DataLayer;
using IMDB.Models;
using IMDB.ViewModels;

namespace IMDB.Controllers
{
    public class UserController : Controller
    {
        private IMDBContext db = new IMDBContext();

        public ActionResult Home()
        {
            return View();
        }


        [HttpGet]
        // GET: Users/Create
        public ActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SignUp(User user, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    string pic = System.IO.Path.GetFileName(file.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("~/ViewAssets/"), pic);

                    file.SaveAs(path);

                    user.Image = pic;
                }
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Login");
            }

            return View();
        }


        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(User user)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    User validuser = db.Users.FirstOrDefault(User => User.Email.ToLower() == user.Email.ToLower() && User.Password == user.Password);

                    if (validuser != null)
                    {
                        Session["Userid"] = validuser.User_ID;
                        Session["UserName"] = validuser.Fname + " " + validuser.Lname;
                        Session["UserImg"] = validuser.Image;
                        return RedirectToAction("EditProfile", new RouteValueDictionary(new { Controller = "User", Action = "EditProfile", Id = validuser.User_ID }));
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Invalid login credentials.");

                }
            }
            catch (NullReferenceException ex)
            {
                ModelState.AddModelError("", "Invalid login credentials.");

            }



            return View();
        }
        [HttpGet]
        public ActionResult EditProfile(int? id)
        {

            if (id != null)
            {
                var user = db.Users.SingleOrDefault(a => a.User_ID == id);
                if (user == null)
                {
                    return HttpNotFound();
                }

                var favMovies = db.UserMovies.Where(x => x.User_ID == id).ToList();
                var favActors = db.UserActors.Where(x => x.User_ID == id).ToList();
                var favDirectors = db.UserDirectors.Where(x => x.User_ID == id).ToList();

                EditProfile edit = new EditProfile
                {
                    User = user,
                    TempUser = user,
                    FavouriteMovies = favMovies,
                    FavouriteActors = favActors,
                    FavouriteDirectors = favDirectors
                };

                return View(edit);
            }
            else
            {
                return RedirectToAction("Home");
            }
        }

        [HttpPost]
        public ActionResult EditProfile(EditProfile profile, HttpPostedFileBase file)
        {

            try
            {
                if (file != null)
                {
                    string pic = System.IO.Path.GetFileName(file.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("~/Images/"), pic);

                    file.SaveAs(path);

                    profile.User.Image = pic;
                }

                db.Entry(profile.User).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("EditProfile", new RouteValueDictionary(new { Controller = "User", Action = "EditProfile", Id = profile.User.User_ID }));

            }
            catch
            {
                return RedirectToAction("EditProfile", new RouteValueDictionary(new { Controller = "User", Action = "EditProfile", Id = profile.User.User_ID }));
            }
        }



        [HttpGet]
        public ActionResult Favourites(int? id)
        {

            if (id != null)
            {
                var user = db.Users.SingleOrDefault(a => a.User_ID == id);
                if (user == null)
                {
                    return HttpNotFound();
                }

                var movies = db.Movies.ToList();
                var actors = db.Actors.ToList();
                var directors = db.Directors.ToList();

                var favMovies = db.UserMovies.Where(x => x.User_ID == id).ToList();
                var favActors = db.UserActors.Where(x => x.User_ID == id).ToList();
                var favDirectors = db.UserDirectors.Where(x => x.User_ID == id).ToList();

                EditProfile edit = new EditProfile
                {
                    User = user,
                    TempUser = user,
                    Movies = movies,
                    Actors = actors,
                    Directors = directors,
                    FavouriteMovies = favMovies,
                    FavouriteActors = favActors,
                    FavouriteDirectors = favDirectors
                };

                return View(edit);
            }
            else
            {
                return RedirectToAction("Home");
            }
        }


        [HttpPost]
        public ActionResult Favourites(EditProfile profile)
        {

            try
            {
                foreach (var favMovieId in profile.FavouriteMoviesIds)
                {
                    var favMovie = db.UserMovies.Single(x => x.Movie_ID == favMovieId && profile.User.User_ID == x.User_ID);
                    db.Entry(favMovie).State = System.Data.Entity.EntityState.Modified;
                }
                foreach (var favActorId in profile.FavouriteActorsIds)
                {
                    var favActor = db.UserActors.Single(x => x.Actor_ID == favActorId && profile.User.User_ID == x.User_ID);

                    db.Entry(favActor).State = System.Data.Entity.EntityState.Modified;
                }
                foreach (var favDirectorId in profile.FavouriteDirectorsIds)
                {
                    var favDirector = db.UserDirectors.Single(x => x.Director_ID == favDirectorId && profile.User.User_ID == x.User_ID);

                    db.Entry(favDirector).State = System.Data.Entity.EntityState.Modified;
                }
                db.SaveChanges();

                return RedirectToAction("EditProfile", new RouteValueDictionary(new { Controller = "User", Action = "EditProfile", Id = profile.User.User_ID }));

            }
            catch
            {
                return RedirectToAction("EditProfile", new RouteValueDictionary(new { Controller = "User", Action = "EditProfile", Id = profile.User.User_ID }));
            }
        }

    }
}

IMDB/Controllers/searchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
 using IMDB.ViewModels;
using System.Data.Entity;
using IMDB.DataLayer;

namespace IMDB.Controllers
{
    public class searchController : Controller
    {

        IMDBContext _context = new IMDBContext();
        SearchViewModel searchVM = new SearchViewModel();
        // GET: Search
        [HttpGet]
        public ActionResult Search()
        {
            searchVM.Actors = _context.Actors.ToList();
            searchVM.Directors = _context.Directors.ToList();
            searchVM.Movies = _context.Movies.ToList();
            return View(searchVM);
        }


        [HttpPost]
        public ActionResult Search(string SearchValue)
        {
            if (SearchValue == null)
            {

            }
            else
            {

                string[] SearchSplit = SearchValue.Split(' ');
                foreach (var item in SearchSplit)
                {
                    searchVM.Actors = _context.Actors.Where(ActorModel => ActorModel.FirstName.ToLower().StartsWith(item) || ActorModel.LastName.ToLower().StartsWith(item) || SearchValue == null);
                    searchVM.Directors = _context.Directors.Where(DirectorModel => DirectorModel.FirstName.ToLower().StartsWith(item) || DirectorModel.LastName.ToLower().StartsWith(item) || SearchValue == null);
                    searchVM.Movies = _context.Movies.Where(MovieModel => MovieModel.Movie_Name.ToLower().StartsWith(item) || SearchValue == null);
                }
            }
            return View(searchVM);
        }
    }
}

IMDB/Views/Users/EditProfile.cshtml
 @model IMDB.ViewModels.EditProfile

<!DOCTYPE html>
<html>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta name="viewport" content="width=device-width , initial-scale = 1.0" />
    <title>Edit Profile</title>
    <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
<!-- Link Swiper's CSS -->
<link rel="stylesheet"
      href="https://unpkg.com/swiper/swiper-bundle.min.css" />
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700&family=Ubuntu:wght@300&display=swap" rel="stylesheet">
<head>
    <style>
        html * {
            font-size: 20PX !important;
            font-family: 'Ubuntu', sans-serif;
        }

        body {
            background: var(--text-color);
            color: var(--bg-color);
            box-sizing: border-box;
            list-style: none;
            text-decoration: none;
        }

        :root {
            --bg-color: white;
            --text-color: black;
            --main-color: red;
        }

        header {
            width: 100%;
            top: 0;
            right: 0;
            z-index: 1000;
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 20px 100px;
            transition: 0.5s;
            box-sizing: border-box;
            border-bottom: 2px solid red;
        }

        .navbar {
            margin-left: 12%;
            display: flex;
            column-gap: 5rem;
            box-sizing: border-box;
            list-style: none;
            text-decoration: none;
        }

            .navbar li {
                position: relative;
                box-sizing: border-box;
                list-style: none;
                text-decoration: none;
            }

            .navbar a {
                font-size: 1rem;
                font-weight: 500;
                color: var(--bg-color);
                box-sizing: border-box;
                list-style: none;
                text-decoration: none;
            }

                .navbar a::after {
                    content: '';
                    width: 0;
                    height: 2px;
                    background: var(--main-color);
                    position: absolute;
                    bottom: -4px;
                    left: 0;
                    transition: 0.4s all linear;
                    box-sizing: border-box;
                    list-style: none;
                    text-decoration: none;
                }

                .navbar a:hover::after,
                .navbar .home-active::after {
                    width: 100%;
                    box-sizing: border-box;
                    list-style: none;
                    text-decoration: none;
                }

        #menu-icon {
            cursor: pointer;
            z-index: 1000001;
            display: none;
            box-sizing: border-box;
            list-style: none;
            text-decoration: none;
        }

        .btn {
            padding: 0.7rem 1.4rem;
            background: var(--main-color);
            color: var(--bg-color);
            font-weight: 400;
            border-radius: 0.5rem;
            box-sizing: border-box;
            list-style: none;
            text-decoration: none;
        }

            .btn:hover {
                background: #fa1216;
                box-sizing: border-box;
                list-style: none;
                text-decoration: none;
            }

        .logo {
            font-size: 24px;
            font-weight: 600;
            color: var(--bg-color);
            display: flex;
            align-items: center;
            column-gap: 0.5rem;
            box-sizing: border-box;
            list-style: none;
            text-decoration: none;
        }

            .logo.bx {
                font-size: 24px;
                color: var(--main-color);
                box-sizing: border-box;
                list-style: none;
                text-decoration: none;
            }


        .div1 {
            position: absolute;
            background-color: black;
            width: 1360px;
            height: 600px;
            margin-left: 250px;
            margin-top: 7.5%;
            border-radius: 40px 0px 40px 0px;
            padding: 20px;
            border-color: var(--main-color);
            border-style: solid;
            border-width: 2px;
        }

        .sign {
            margin-left: 370px;
            font-size: 30px;
            font-weight: bold;
        }

        .div3, .div4, .div5, .div6, .div10 {
            margin-left: 50px;
        }
      
        a {
            text-decoration: none;
        }

        .div8 {
            border: 0.5px solid #999;
            width: 0px;
            height: 500px;
            margin-top: -420px;
            margin-left: 850px;
            border-color: var(--bg-color);
            border-style: solid;

        }

        .div9 {
            margin-left: 925px;
            width: 300px;
        }

        input {
            background-color: var(--text-color);
            width: 300px;
            border: none;
            border-bottom: 1px solid white;
            padding: 11px 20px 11px 50px;
            outline: none;
            color:white;

        }


        .icon1 {
            position: absolute;
            margin-left: 7px;
            margin-top: 05px;
        }

        .icon2 {
            position: absolute;
            margin-left: 7px;
            margin-top: 05px;
            font-size: 1px;
        }

        img {
            width: 30px;
        }

        .update {
            border: none;
            outline: 0;
            display: inline-block;
            padding: 8px;
            color: white;
            background-color: #000;
            text-align: center;
            cursor: pointer;
            width: 100%;
            font-size: 18px;
            height:70px;
        }




        .div6 label {
            margin-left: 90px;
        }



        .p {
            position: absolute;
            font-size: smaller;
            width: 250px;
            margin-left: -300px;
            margin-top: 50px;
            height: 0px;
            color: white;
        }
        ::placeholder {  
         color: white;
         opacity: 1;  
        }
        .profile {
            margin-left: 1000px;
             margin-top: -490px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            max-width: 250px;
            text-align: center;
 border-color:white;
border-style:solid;
        }
 
    </style>
</head>

<body>
    @using (Html.BeginForm("EditProfile", "Users", new { enctype = "multipart/form-data" }))
    {
        <header>
            <a href="#" class="logo">

                <i class='bx bxl-imdb'></i> IMDB
            </a>
            <div class="bx bx-menu" id="menu-icon"></div>
            <!--Menu-->
            <ul class="navbar">
                <li> <a href="#home" class="home-active">Edit Profile</a></li>
                <li> <a href="#Movies">Movies</a></li>
                <li> <a href="#Movies">Actors</a></li>
                <li> <a href="#Movies">Directors</a></li>
            </ul>

        </header>
        <div class="div1">
            <div class="div2">
                <p class="sign">User Setting</p>
            </div>

            <br>
            <br>

            <div class="div3">

                <i class="icon1"> <img src="~/ViewAssets/id-card.png" alt="logo"></i>

                @Html.TextBoxFor(Model => Model.user.Fname, new { @class = "input" })
                <i class="icon2"> <img src="~/ViewAssets/id-card.png" alt="logo"></i>
                @Html.TextBoxFor(Model => Model.user.Lname, new { @class = "input" })


            </div>
            <br><br>
            <div class="div4">

                <i class="icon1"> <img src="~/ViewAssets/mail (2).png" alt="logo"></i>

                @Html.TextBoxFor(Model => Model.user.Email, new { @class = "input" })

                <i class="icon1"> <img src="~/ViewAssets/lock (1).png" alt="logo"></i>

                @Html.TextBoxFor(Model => Model.user.Password, new { @class = "input" })

            </div>
            <br> <br>
            <div class="div5">




            </div>
            <br>
            <br>
            <div class="div6">




            </div>


 


            <div class="div8">

            </div>
            <div class="profile">
            <img src="@Url.Content("~/ViewAssets/"+Model.user.Image)" alt="" style="width:100% "  />  
                <h1>@Model.user.Fname @Model.user.Lname</h1>
             </div>
        </div>
    }
</body>
</html>
 

IMDB/Views/Users/Home.cshtml
@model IMDB.Models.User

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta name="viewport" content="width=device-width , initial-scale = 1.0" />
    <title>IMDB Website</title>
    <link rel="stylesheet" href="~/Content/Styles.css" />
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    <!-- Link Swiper's CSS -->
    <link rel="stylesheet"
          href="https://unpkg.com/swiper/swiper-bundle.min.css" />
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700&family=Ubuntu:wght@300&display=swap" rel="stylesheet">
    
</head>
<body>
    <!--Navbar-->
    <header>
        <a href="#" class="logo">

            <i class='bx bxl-imdb'></i> IMDB
        </a>
        <div class="bx bx-menu" id="menu-icon"></div>
        <!--Menu-->
        <ul class="navbar">
            <li>@Html.ActionLink("Search","search", "Search",new {id ="" }, new { @class = "btn" })</li>
            <li> <a href="#home" class="home-active">Home</a></li>
            <li> <a href="#Movies">Movies</a></li>
            <li> <a href="#Movies">Actors</a></li>
            <li> <a href="#Movies">Directors</a></li>
        </ul>
        <a>@Html.ActionLink("SignUp", "SignUp",null , new { @class = "btn" })</a>

    </header>

    <!--home-->
    <section class="home swiper" id="home">
        <!--First-->
        <div class="swiper-wrapper">
            <div class="swiper-slide container">
                <img src="~/ViewAssets/unknown (1).png" alt="">
                <div class="home-text">
                    <span></span>
                    <h1>Harry Potter <br>and the Deathly Hallows</h1>
                    <a href="#" class="btn">Rate Now</a>
                    <a href="#" class="rate">
                        <i class='bx bx-star'></i>
                    </a>
                </div>
            </div>
            <div class="swiper-slide container">
                <img src="~/ViewAssets/home3.jpg" alt="">
                <div class="home-text">
                    <span>Marvel Universe</span>
                    <h1>Spider-Man<br> Far From Home</h1>
                    <a href="#" class="btn">Rate Now</a>
                    <a href="#" class="rate">
                        <i class='bx bx-star'></i>
                    </a>
                </div>
            </div>
            <!--Third-->

            <div class="swiper-slide container">
                <img src="~/ViewAssets/home2.jpg" alt="">
                <div class="home-text">
                    <span>Marvel Universe</span>
                    <h1>Avengers<br> Infinity War</h1>
                    <a href="#" class="btn">Rate Now</a>
                    <a href="#" class="rate">
                        <i class='bx bx-star'></i>
                    </a>
                </div>
            </div>
        </div>


        <div class="swiper-pagination"></div>

    </section>

    <section class="movies" id="movies">
        <h2 class="heading">Top Movies</h2>
        <!--MOVIES-->
        <div class="movies-container">
            <!--box1-->
            <div class="box">
                <div class="box-img">
                     <img src="~/ViewAssets/doctorstrange.png" alt="" />
                </div>
                <h3>Doctor Strange in the Multiverse of Madness</h3>
                <span>2h 6m | Adventure</span>
            </div>
            <!--box2-->
            <div class="box">
                <div class="box-img">
                    <img src="~/ViewAssets/m1.jpg" alt="" />
                </div>
                <h3>Venom</h3>
                <span>120 min | Action</span>
            </div>
            <!--box3-->
            <div class="box">
                <div class="box-img">
                    <img src="~/ViewAssets/Screenshot 2022-04-26 071041.png" alt="" />
                </div>
                <h3>Thor: Love and Thunder</h3>
                <span>120 min | Adventure</span>
            </div>
            <!--box4-->
            <div class="box">
                <div class="box-img">
                    <img src="~/ViewAssets/m3.jpg" alt="" />
                </div>
                <h3>Batman Vs Superman</h3>
                <span>120 min | Action</span>
            </div>
            <!--box5-->
            <div class="box">
                <div class="box-img">
                    <img src="~/ViewAssets/m4.jpg" alt="" />
                </div>
                <h3>John Wick 2</h3>
                <span>120 min | Action</span>
            </div>
            <!--box6-->

            <div class="box">
                <div class="box-img">
                    <img src="~/ViewAssets/m5.jpg" alt="" />
                </div>
                <h3>Batman Vs Superman</h3>
                <span>120 min | Action</span>
            </div>
            <!--box7-->

            <div class="box">
                <div class="box-img">
                    <img src="~/ViewAssets/philosophers-stone-20-years-of-movie-magic-harry-poster.jpg" alt="" />
                </div>
                <h3>Harry Potter and the Philosopher's Stone</h3>
                <span>
                    2h 10m | PG-13
                </span>
            </div>
            <!--box8-->

            <div class="box">
                <div class="box-img">
                    <img src="~/ViewAssets/chamber-of-secrets-theatrical-poster-1050x0-c-default.jpg" alt="" />
                </div>
                <h3>Batman Vs Superman</h3>
                <span>
                    2h 10m | PG-13
                </span>
            </div>
            <!--box9-->

            <div class="box">
                <div class="box-img">
                    <img src="~/ViewAssets/noway home.png" alt="" />
                </div>
                <h3>Spider-Man: No Way Home</h3>
                <span>120 min | Adventure</span>
            </div>
            <!--box10-->

            <div class="box">
                <div class="box-img">
                    <img src="~/ViewAssets/hp2.png" alt="" />
                </div>
                <h3>Harry Potter and the Deathly Hallows: Part 1</h3>
                <span>
                    2h 26m | PG-13
                </span>
            </div>

        </div>
    </section>


    <!-- Swiper JS -->
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <script src="~/Content/JavaScript.js"></script>
</body>
</html>